# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ForcastDialogView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForCastDialogView(object):
    def setupUi(self, ForCastDialogView):
        ForCastDialogView.setObjectName("ForCastDialogView")
        ForCastDialogView.resize(516, 444)
        self.TitleLabel = QtWidgets.QLabel(ForCastDialogView)
        self.TitleLabel.setGeometry(QtCore.QRect(90, 40, 301, 61))
        font = QtGui.QFont()
        font.setFamily("ethnocentric")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.forcastLabel = QtWidgets.QLabel(ForCastDialogView)
        self.forcastLabel.setGeometry(QtCore.QRect(80, 130, 291, 121))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forcastLabel.setFont(font)
        self.forcastLabel.setObjectName("forcastLabel")
        self.vedioButton = QtWidgets.QPushButton(ForCastDialogView)
        self.vedioButton.setGeometry(QtCore.QRect(350, 330, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.vedioButton.setFont(font)
        self.vedioButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vedioButton.setIcon(icon)
        self.vedioButton.setIconSize(QtCore.QSize(150, 150))
        self.vedioButton.setObjectName("vedioButton")
        self.fileLinkButton = QtWidgets.QCommandLinkButton(ForCastDialogView)
        self.fileLinkButton.setGeometry(QtCore.QRect(90, 330, 151, 48))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/arrow.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileLinkButton.setIcon(icon1)
        self.fileLinkButton.setIconSize(QtCore.QSize(30, 30))
        self.fileLinkButton.setObjectName("fileLinkButton")
        self.fileNameLabel = QtWidgets.QLabel(ForCastDialogView)
        self.fileNameLabel.setGeometry(QtCore.QRect(100, 390, 191, 31))
        self.fileNameLabel.setText("")
        self.fileNameLabel.setObjectName("fileNameLabel")

        self.retranslateUi(ForCastDialogView)
        QtCore.QMetaObject.connectSlotsByName(ForCastDialogView)

    def retranslateUi(self, ForCastDialogView):
        _translate = QtCore.QCoreApplication.translate
        ForCastDialogView.setWindowTitle(_translate("ForCastDialogView", "Forcast"))
        self.TitleLabel.setText(_translate("ForCastDialogView", "Class prediction"))
        self.forcastLabel.setText(_translate("ForCastDialogView", "预测结果为："))
        self.fileLinkButton.setText(_translate("ForCastDialogView", "上传音频文件"))
